# Generated by Django 4.2.7 on 2025-09-01 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('chat_id', models.BigIntegerField()),
                ('reason', models.TextField()),
            ],
            options={
                'db_table': 'bans',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChatSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('filter_enabled', models.BooleanField(default=True)),
                ('welcome_enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'chat_settings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'moderators',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Punishment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('chat_id', models.BigIntegerField()),
                ('punishment_type', models.CharField(choices=[('kick', 'Kick'), ('ban', 'Ban'), ('mute', 'Mute'), ('warn', 'Warning')], max_length=10)),
                ('reason', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('moderator_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'punishments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('chat_id', models.BigIntegerField()),
                ('warn_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'warnings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TelegramChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('chat_type', models.CharField(default='group', max_length=50)),
                ('member_count', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
