# Generated by Django 4.2.7 on 2025-09-01 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='telegramuser',
            table='telegramuser',
        ),
    ]
